### ISSUE TITLE
Request for GitHub username

### ISSUE THREAD

**Issue by phuctm97** [evengers/geocode_neo4j#1]
Hi @evengers,

I'm Phuc and I'm going to start an organization of name `evengers`, which is your username. I've just checked out that you didn't use this account much, so can you please help me to change your username so that I can use the name. I'll really appreciate it and willing to pay you a bit for that.

Thanks.

**Comment by evengers** [comment]
Sorry ... not possible

**Comment by phuctm97** [comment]
Thank for yout reply. I understand that’s a weird request. But one last
question, is there anything I can do to make that posible?

Sincerely.

**Comment by evengers** [comment]
We use „evengers“ actively in a number of contexts so It is highly unlikely that we have anything to discuss ... but you can  always specify how you would intend to use it and but a concrete proposal on the table.

**Comment by phuctm97** [comment]
Okay, I got the situation. Thank for your reply anyway!
